[package]
name = "tab-synth"
version = "0.1.0"
authors = ["Elias <elre233@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.11.0"
clap = "2.33.3"
itertools = "0.9.0"