[package]
name = "tab-synth"
version = "0.1.0"
authors = ["Elias <elre233@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
synth = "0.11.0"
pitch_calc = "0.12.0"
portaudio = "0.7.0"
sample = "0.11.0"